# Site settings
title: 'Blinktrade, Inc.'
email: contact@blinktrade.com
description: "Blinktrade Landing Page"
baseurl: ""
url: "http://dev.blinktrade.com"

# Build settings
markdown: kramdown

source: .
destination: ./_site
plugins: ./_plugins
paginate: 5
paginate_path: "blog/page:num"

permalink: /:title/